services:
  authors-api:
    build:
      context: .
      dockerfile: src/Services/Authors/Authors.Api/Dockerfile
    ports:
      - "8081:8080"

  posts-api:
    build:
      context: .
      dockerfile: src/Services/Posts/Posts.Api/Dockerfile
    environment:
      Services__Authors__BaseUrl: http://authors-api:8080
    ports:
      - "8080:8080"
    depends_on:
      - authors-api
